# Generated by Django 5.2.7 on 2026-08-16 15:01

import apps.common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.playlist_cover_upload_to, validators=[apps.common.uploads.validate_image_file]),
        ),
    ]
