# Generated by Django 5.2.7 on 2026-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('role', models.CharField(choices=[('listener', 'Listener'), ('artist', 'Artist'), ('support', 'Support'), ('admin', 'Admin')], default='listener', max_length=20)),
                ('artist_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=20)),
                ('subscription', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
