# Generated by Django 5.2.7 on 2026-08-16 15:01

import apps.common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.user_avatar_upload_to, validators=[apps.common.uploads.validate_image_file]),
        ),
    ]
