# Generated by Django 5.2.7 on 2026-08-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.URLField(blank=True, default='', max_length=500)),
                ('released_at', models.DateField()),
                ('listeners', models.PositiveIntegerField(default=0)),
                ('early_access', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=100)),
                ('collaborators', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='users.user')),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.URLField(blank=True, default='', max_length=500)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('listeners', models.PositiveIntegerField(default=0)),
                ('released_at', models.DateField()),
                ('early_access', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=100)),
                ('collaborators', models.JSONField(blank=True, default=list)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('audio_name', models.CharField(blank=True, default='', max_length=255)),
                ('audio_size', models.PositiveIntegerField(default=0)),
                ('audio_type', models.CharField(blank=True, default='', max_length=100)),
                ('audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='users.user')),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
    ]
