# Generated by Django 5.2.7 on 2026-08-16 15:01

import apps.common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.uploads.track_audio_upload_to, validators=[apps.common.uploads.validate_audio_file]),
        ),
        migrations.AddField(
            model_name='track',
            name='external_audio_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.album_cover_upload_to, validators=[apps.common.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.track_cover_upload_to, validators=[apps.common.uploads.validate_image_file]),
        ),
    ]
